basscollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('basses/', views.bass_index, name="bass_index"),
    path('basses/<int:bass_id>', views.bass_details, name="bass_details"),
    path('basses/create/', views.BassCreate.as_view(), name="bass_create"),
    path('basses/<int:pk>/update/', views.BassUpdate.as_view(), name="bass_update"),
    path('basses/<int:pk>/delete/', views.BassDelete.as_view(), name='bass_delete'),
    path('basses/<int:bass_id>/add_string/', views.add_string, name='add_string'),

    path('basses/<int:bass_id>/assoc_amp/<int:amp_id>/', views.assoc_amp, name='assoc_amp'),
    path('basses/<int:bass_id>/unassoc_amp/<int:amp_id>/', views.unassoc_amp, name='unassoc_amp'),

    path('amps/', views.AmpList.as_view(), name="amp_index"),
    path('amps/<int:pk>/', views.AmpDetail.as_view(), name="amp_detail"),
    path('amps/create/', views.AmpCreate.as_view(), name="amp_create"),
    path('amps/<int:pk>/delete/', views.AmpDelete.as_view(), name="amp_delete"),
]

main_app/models.py
from django.db import models
from django.urls import reverse

VARIETIES = (
    ('R', 'Roundwound'),
    ('H', 'Halfround'),
    ('F', 'Flatwound'),
    ('T', 'Tapewound'),
)

class Amp(models.Model):
    make = models.CharField(max_length=15)
    model = models.CharField(max_length=20)
    wattage = models.IntegerField()
    variety = models.CharField(max_length=20)
    
    def __str__(self):
        return f'{self.model} ({self.id})'

    def get_absolute_url(self):
        return reverse('amp_detail', kwargs={'pk': self.id})


class Bass(models.Model):
    make = models.CharField(max_length=15)
    model = models.CharField(max_length=20)
    scale = models.IntegerField()
    color = models.CharField(max_length=20)
    construction = models.CharField(max_length=50)
    amps = models.ManyToManyField(Amp)

    def __str__(self):
        return f'{self.model} ({self.id})'

    def get_absolute_url(self):
        return reverse('bass_details', kwargs={'bass_id': self.id})

class Strings(models.Model):
    make = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    variety = models.CharField(
        # Name of the field in UI 
        'Type',
        max_length=1,
        choices = VARIETIES,
        default = VARIETIES[0][0]
    )
    bass = models.ForeignKey(
        Bass,
        # Deletes Strings associated with Bass
        on_delete=models.CASCADE
    )
    
    def __str__(self):
        return f'{self.make} {self.model} {self.get_variety_display()}'

main_app/forms.py
from django.forms import ModelForm
from .models import Strings

class StringForm(ModelForm):
    class Meta:
        model = Strings
        fields = ['make', 'model', 'variety']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Bass, Amp
from .forms import StringForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

# we need to pass data, which we do with objects/dicts. this goes to the template!
def bass_index(request):
    basses = Bass.objects.all()
    return render(request, 'basses/index.html', {
        'basses' : basses
    })

def bass_details(request, bass_id):
    bass = Bass.objects.get(id=bass_id)
    # Exclude amps not associated with bass
    id_list = bass.amps.all().values_list('id')
    amps_bass_doesnt_have = Amp.objects.exclude(id__in=id_list)
    # instantiate StringsForm to be rendered in the details template
    string_form = StringForm()
    return render(request, 'basses/details.html', { 
        'bass':bass, 
        'amps': amps_bass_doesnt_have,
        'string_form': string_form 
    })


class BassCreate(CreateView):
    model = Bass
    fields = ['make', 'model', 'scale', 'color', 'construction']

class BassUpdate(UpdateView):
    model = Bass
    fields = '__all__'

class BassDelete(DeleteView):
    model = Bass
    success_url = '/basses'

def add_string(request, bass_id):
    form = StringForm(request.POST)
    if form.is_valid():
        new_string = form.save(commit=False)
        new_string.bass_id = bass_id
        new_string.save()
    return redirect('bass_details', bass_id=bass_id)

class AmpCreate(CreateView):
    model = Amp
    fields = '__all__'

class AmpList(ListView):
    model = Amp
    fields = '__all__'

class AmpDetail(DetailView):
    model = Amp
    fields = '__all__'

class AmpDelete(DeleteView):
    model = Amp
    fields = '__all__'
    success_url = '/amps'

def assoc_amp(request, bass_id, amp_id):
    Bass.objects.get(id=bass_id).amps.add(amp_id)
    return redirect('bass_details', bass_id=bass_id)

def unassoc_amp(request, bass_id, amp_id):
    Bass.objects.get(id=bass_id).amps.remove(amp_id)
    return redirect('bass_details', bass_id=bass_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>about this site...</h1>
<hr>
<p class="flow-text">Hello! I'm just a regular person who likes bass guitars, 
    and this website is where I'll be compiling basses that I find interesting! 
    So, you can check out what I've found and maybe tell me your thoughts. 
    Let's chat about bass guitars! 🎸</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Bass Wishlist</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>  
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;bass wishlist</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">about</a></li>
          <li><a href="{% url 'bass_create' %}">add bass</a></li>
          <li><a href="{% url 'amp_create' %}">add amp</a></li>
          <li><a href="{% url 'bass_index' %}">view all basses</a></li>
          <li><a href="{% url 'amp_index' %}">view all amps</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Bass Wishlist &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/basses/details.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
    <div class="card-content">
        <span class="card-title">{{ bass.make }} {{bass.model }}</span>
        <p>Color: {{ bass.color }}</p>
        <p>Scale: {{ bass.scale }}</p>
        <p>Material: {{ bass.construction | linebreaks}}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'bass_update' bass.id %}">Edit</a>
        <a href="{% url 'bass_delete' bass.id %}">Delete</a>
    </div>
</div>


<div class="card">
    <div class="card-content">
        <p class="card-title"> Strings </p>
        <div class="col s6">
            <form action="{% url 'add_string' bass.id %}" method="POST">
                {% csrf_token %}
                {{ string_form.as_p }}
                <input type="submit" class="btn" value="Add Strings">
            </form>
        </div>
        <table class="striped">
            <thead>
                <tr>
                    <th>Brand</th>
                    <th>Model</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
                {% for strings in bass.strings_set.all %}
                <tr>
                    <td>{{strings.make}}</td>
                    <td>{{strings.model}}</td>
                    <td>{{strings.get_variety_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="card">
    <div class="row">
        <div class="col s6">
          <p class="card-title"> Amps to consider with {{ bass.make }} {{ bass.model }}</p>
          {% if bass.amps.count %}
            {% for amp in bass.amps.all %}
              <div class="card">
                <div class="card-content">
                  <span class="card-title">
                    {{amp.make}} {{amp.model}} - {{amp.wattage}} {{amp.variety}} Amp
                  </span>
                </div>
                <div>
                    <form action="{% url 'unassoc_amp' bass.id amp.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn">Remove</button>
                    </form>
                </div>
              </div>
            {% endfor %}
          {% endif %}
        </div>
    </div>
</div>

<div class="card">
    <div class="row">
        <div class="col s6">
            <p class="card-title"> Other Amps </p>
            {% if amps.count %}
                {% for amp in amps.all %}
                    <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                        {{amp.make}} {{amp.model}} - {{amp.wattage}} {{amp.variety}} Amp
                        </span>
                    </div>
                    <div>
                        <form action="{% url 'assoc_amp' bass.id amp.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn">Add</button>
                        </form>
                    </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
</div>

<script>
    const selectEl = document.getElementById('id_variety');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/basses/index.html
{% extends 'base.html' %}
{% block content %}

<h1>bass wishlist</h1>
<!-- This 'basses' is coming from the dict we passed through in the basses_index fn in views -->
<!-- Use DTL (Django Template Language), not a python for loop -->
{% for bass in basses %}
    <a href="{% url 'bass_details' bass.id %}">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ bass.make }} {{bass.model }}</span>
                <p>Color: {{ bass.color }}</p>
                <p>Scale: {{ bass.scale }}</p>
                <p>Material: {{ bass.construction | linebreaks}}</p>
            </div>
        </div>
    </a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1> welcome! </h1>
<hr>
{% endblock %}

main_app/templates/main_app/amp_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Amp</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <!-- post request  -->
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'amp_detail' amp.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/amp_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>amp details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ amp.make }} {{ amp.model }}</span>
        <p>Wattage: {{ amp.wattage }}</p>
        <p>Type: {{ amp.variety }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'amp_delete' amp.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/amp_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1 class="teal-text"> Edit {{bass.model}} </h1>
{% else %}
    <h1 class="teal-text"> Add a new Bass </h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form.as_p}}
    </table>
    <button type="submit" class="btn">Confirm</button>
</form>

{% endblock %}

main_app/templates/main_app/amp_list.html
{% extends 'base.html' %}
{% block content %}

<h1>amps list</h1>

{% for amp in amp_list %}
  <a href="{% url 'amp_detail' amp.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ amp.make }} {{ amp.model }}</span>
            <p>Wattage: {{ amp.wattage }}</p>
            <p>Type: {{ amp.variety }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/bass_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Bass</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <!-- post request  -->
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'bass_details' bass.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/bass_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1 class="teal-text"> Edit {{bass.model}} </h1>
{% else %}
    <h1 class="teal-text"> Add a new Bass </h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form.as_p}}
    </table>
    <button type="submit" class="btn">Confirm</button>
</form>

{% endblock %}